config/routes.rb
Rails.application.routes.draw do
  get 'admin/index', to: 'admin#index', as: :admin
  get 'search/index', to: 'search#index', as: :search
  get 'movies/index', to: 'movies#index', as: :movies
  get 'musics/index', to: 'musics#index', as: :musics
  get 'images/index', to: 'images#index', as: :images

  resources :shared_folders
  resources :users, except: [:show, :update]
  put 'user/:id/update', to: 'users#update', as: :update_user

  resources :attachments, except: [:index, :show, :create] do
    post 'authorize'
    post 'create', to: 'attachments#create', as: :create
    member do
      get 'show_image/show_image.gif', to: 'attachments#show_image'
      get 'show_thumb', to: 'attachments#show_thumb'
    end
  end

  get 'attachments/:page', to: 'attachments#index', as: :attachments
  get 'attachment/:page/show', to: 'attachments#show', as: :show_attachment


  ########  files controller #############
  post 'files/move', to: 'files#move'
  post 'files/copy', to: 'files#copy'
  post 'files/share_with', to: 'files#share_with'
  post 'files/delete', to: 'files#delete'
  post 'files/new_file', to: 'files#new_file'
  post 'files/rename', to: 'files#rename'
  post 'files/upload', to: 'files#upload'
  get 'files/download', to: 'files#download'
  get 'files/text_preview', to: 'files#text_preview'
  get 'files/preview', to: 'files#preview'
  get 'files/show_image', to: 'files#show_image'
  get 'files/show_image_thumb', to: 'files#show_image_thumb'
  get 'files/stream_file', to: 'files#stream_file'
  get 'files/video_thumb', to: 'files#video_thumb'
  ########  files controller #############



  ########  homes controller #############
  get "/", to: 'home#index'
  get :refresh_sidebar, to: 'homes#refresh_sidebar'
  ########  homes controller #############

  ########  images controller #############
  get :index, to: 'images#index'
  post :manipulate_image, to: 'images#manipulate_image'
  ########  homes controller #############

  devise_for :users
  root to: 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :attachments
  has_many :shared_folders, foreign_key: 'owner_id'
  has_many :friends_folders, foreign_key: 'friend_id', class_name: 'SharedFolder'

  after_create :create_data_folder


  def get_folders
    friendsfolders = self.friends_folders.map{|sf| AcFile.new(sf.path) }
    [data_folder] | friendsfolders.select do |sharedfolder|
      friendsfolders.reject{|sf| sf == sharedfolder || sf.include?(sharedfolder) }
    end
  end

  def create_data_folder
    FileUtils.mkdir_p data_path("first\ folder")
    FileUtils.cp File.join(Rails.root, "data", "templates", "readme"), data_path
  end

  def data_path sub_path=""
    File.join(File.join(Rails.root, "data", name), sub_path)
  end

  def data_folder
    return @data_folder if @data_folder
    @data_folder = AcFile.new(self.data_path)
    @data_folder
  end

  def share(file, friend, permission="read")
    file = file.is_a?(AcFile) ? file : AcFile.new(file)
    if self.data_folder.include?(file) || file.path == self.data_folder.path
      sf = SharedFolder.new(friend: friend, path: file.path, permission: permission)
      self.shared_folders<< sf
      sf.save
      sf
    else
      nil
    end
  end

  def can_change_file(file)
    spath = Pathname.new(self.data_path).realpath.to_s
    opath = Pathname.new(file).realpath.to_s
    !opath.gsub!(/^#{spath}/,'').nil?
  end

  def allowed_to_change_files(*files)
    !files.reject{|file| self.can_change_file(file) }.any?
  end

  def allowed_to_visit_files(*files)
    true
  end

  def to_json(*arguments)
    hash= {}
    hash[:name]= self.name
    hash[:username] = self.name
    hash[:id] = self.id
    hash[:shared_folders] =self.shared_folders
    hash[:friends_folders] =self.shared_folders
    hash.to_json
  end

  def admin?
    "#{self.role}" == 'admin'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @title = "Users"
    @users = User.all
  end

  def new
    @title = pat(:new_title, :model => 'user')
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      @title = pat(:create_title, :model => "user #{@user.id}")
      flash[:success] = pat(:create_success, :model => 'User')
      params[:save_and_continue] ? redirect(url(:users, :index)) : redirect(url(:users, :edit, :id => @user.id))
    else
      @title = pat(:create_title, :model => 'user')
      flash.now[:error] = pat(:create_error, :model => 'user')
    end
  end

  def edit
    @title = pat(:edit_title, :model => "user #{params[:id]}")
    @user = User.find(params[:id])
    unless @user
      flash[:warning] = pat(:create_error, :model => 'user', :id => "#{params[:id]}")
      render status: 404
    end
  end

  def update
    @title = pat(:update_title, :model => "user #{params[:id]}")
    @user = User.find(params[:id])
    if @user
      if @user.update(params[:user])
        flash[:success] = pat(:update_success, :model => 'User', :id =>  "#{params[:id]}")
        params[:save_and_continue] ?
          redirect(users_path) :
          redirect(edit_user_path(@user.id))
      else
        flash.now[:error] = pat(:update_error, :model => 'user')
        render 'edit'
      end
    else
      flash[:warning] = pat(:update_warning, :model => 'user', :id => "#{params[:id]}")
      render status: 404
    end
  end

  def destroy
    @title = "Users"
    user = User.find(params[:id])
    if user
      if user != current_user && user.destroy
        flash[:success] = pat(:delete_success, :model => 'User', :id => "#{params[:id]}")
      else
        flash[:error] = pat(:delete_error, :model => 'user')
      end
      redirect users_path
    else
      flash[:warning] = pat(:delete_warning, :model => 'user', :id => "#{params[:id]}")
      render status:  404
    end
  end

  def destroy_many
    @title = "Users"
    unless params[:user_ids]
      flash[:error] = pat(:destroy_many_error, :model => 'user')
      redirect users_path
    end
    ids = params[:user_ids].split(',').map(&:strip)
    users = User.all(:id => ids)

    if users.include? current_user
      flash[:error] = pat(:delete_error, :model => 'user')
    elsif users.destroy

      flash[:success] = pat(:destroy_many_success, :model => 'Users', :ids => "#{ids.to_sentence}")
    end
    redirect users_path
  end
end

app/views/users/_form.haml
- error = @user.errors.key?(:name) && @user.errors[:name].count > 0
%fieldset.control-group{:class => error ? 'has-error' : ''}
  =f.label :name, :class => 'control-label'
  .controls
    =f.text_field :name, :class => 'form-control input-large input-with-feedback', :autofocus => true
    %span.help-inline=error ? f.error_message_on(:name, :class => 'text-error') : '' #pat(:example)
- error = @user.errors.key?(:username) && @user.errors[:username].count > 0
%fieldset.control-group{:class => error ? 'has-error' : ''}
  =f.label :username, :class => 'control-label'
  .controls
    =f.text_field :username, :class => 'form-control input-large input-with-feedback', :autofocus => true
    %span.help-inline=error ? f.error_message_on(:username, :class => 'text-error') : '' #pat(:example)
- error = @user.errors.key?(:surname) && @user.errors[:surname].count > 0
%fieldset.control-group{:class => error ? 'has-error' : ''}
  =f.label :surname, :class => 'control-label'
  .controls
    =f.text_field :surname, :class => 'form-control input-large input-with-feedback'
    %span.help-inline=error ? f.error_message_on(:surname, :class => 'text-error') : '' #pat(:example)
- error = @user.errors.key?(:email) && @user.errors[:email].count > 0
%fieldset.control-group{:class => error ? 'has-error' : ''}
  =f.label :email, :class => 'control-label'
  .controls
    =f.text_field :email, :class => 'form-control input-large input-with-feedback'
    %span.help-inline=error ? f.error_message_on(:email, :class => 'text-error') : '' #pat(:example)
- error = @user.errors.key?(:password) && @user.errors[:password].count > 0
%fieldset.control-group{:class => error ? 'has-error' : ''}
  =f.label :password, :class => 'control-label'
  .controls
    =f.password_field :password, :class => 'form-control input-large input-with-feedback'
    %span.help-inline=error ? f.error_message_on(:password, :class => 'text-error') : '' #pat(:example)
- error = @user.errors.key?(:password_confirmation) && @user.errors[:password_confirmation].count > 0
%fieldset.control-group{:class => error ? 'has-error' : ''}
  =f.label :password_confirmation, :class => 'control-label'
  .controls
    =f.password_field :password_confirmation, :class => 'form-control input-large input-with-feedback'
    %span.help-inline=error ? f.error_message_on(:password_confirmation, :class => 'text-error') : pat(:example)
- error = @user.errors.key?(:role) && @user.errors[:role].count > 0
%fieldset.control-group{:class => error ? 'has-error' : ''}
  =f.label :role, :class => 'control-label'
  .controls
    =f.text_field :role, :class => 'form-control input-large input-with-feedback'
    %span.help-inline=error ? f.error_message_on(:role, :class => 'text-error') : '' #pat(:example)

.form-actions
  =f.submit pat(:save), :class => 'btn btn-primary'
  &nbsp;
  =f.submit pat(:save_and_continue), :class => 'btn btn-info', :name => 'save_and_continue'
  &nbsp;
  -#=link_to pat(:cancel), url(:Users, :index), :class => 'btn btn-default'
  =link_to pat(:cancel), users_index_path, :class => 'btn btn-default'

app/views/users/edit.haml
%ul.nav.nav-tabs
  %li=link_to icon_tag(:list, pat(:list)), users_path #url(:Users, :index)
  %li=link_to icon_tag(:plus, pat(:new)), new_user_path #url(:Users, :new)
  %li.active=link_to icon_tag(:edit, pat(:edit)), edit_user_path(@user.id)#url(:Users, :edit, :id => @User.id)

.tabs-content
  -#url(:Users, :update, :id => @User.id)
  = form_for @user, :method => :put, :class => 'form-horizontal' do |f|
    =render partial: 'users/form', :locals => { :f => f }

app/views/users/index.haml
%ul.nav.nav-tabs
  %li.active=link_to icon_tag(:list, pat(:list)), users_index_path #url(:Users, :index)
  %li=link_to icon_tag(:plus, pat(:new)), users_new_path #url(:Users, :new)

.tabs-content
  %table#list.table.table-striped.table-hover.table-condensed
    %thead
      %tr
        %th.header.list-menu
          .dropdown
            %a.list-menu-toggle.dropdown-toggle{:href => '#', :'data-toggle' => :dropdown}
              =icon_tag :magic
              %span.caret
            %ul.list-menu.dropdown-menu{:role => :menu}
              %li.list-menu-wrapper=link_to icon_tag(:check, pat(:select_all)), '#', :id => 'select-all', :class => 'list-menu-link'
              %li.list-menu-wrapper.list-menu-wrapper-disabled
                =link_to icon_tag(:'check-empty', pat(:deselect_all)), '#', :id => 'deselect-all', :class => 'list-menu-link list-menu-link-disabled'
              %li.list-menu-divider.divider
              %li.list-menu-wrapper.list-menu-wrapper-disabled
                =link_to icon_tag(:trash, pat(:delete_selected)), '#', :id => 'delete-selected', :class => 'list-menu-link list-menu-link-disabled'
                .list-menu-popover-delete-selected.popover.right
                  .arrow
                  %h3.popover-title=pat(:delete_selected_title)
                  .popover-content
                    = form_tag destroy_many_users_path, :method => :delete do
                      =hidden_field_tag :user_ids, :'data-delete-many-ids' => true
                      =submit_tag pat(:delete), :class =>'list-menu-popover-delete-selected-btn btn btn-danger btn-small'
                      .btn.btn-default.btn-small.cancel=pat(:cancel)
        %th.header= mat(:user, :id)
        %th.header= mat(:user, :name)
        %th.header= mat(:user, :surname)
        %th.header= mat(:user, :email)
        %th.header.list-row-action-header

    %tbody
      -@users.each do |user|
        %tr.list-row
          %td.list-column.list-selectable
            =check_box_tag 'user_ids[]', :value => user.id, :class => 'list-selectable-checkbox'
          %td.list-column=user.id
          %td.list-column=user.name
          %td.list-column=user.surname
          %td.list-column=user.email
          %td.list-column.list-row-action
            .list-row-action-wrapper
              =link_to icon_tag(:edit), :href => edit_user_path(user.id), :rel => :tooltip, :title => "#{pat(:edit)} user", :class => 'list-row-action-wrapper-link'
              =link_to icon_tag(:trash), :rel => :tooltip, :title => "#{pat(:delete)} user", :class => 'list-row-action-delete-one list-row-action-wrapper-link'
              .popover.list-row-action-popover-delete-one.left
                .arrow
                %h3.popover-title=pat(:delete, :model => "user")
                .popover-content
                  = form_tag destroy_user_path(user.id), :method => :delete do
                    =submit_tag pat(:delete), :class =>'list-row-action-popover-delete-one-btn btn btn-danger btn-small'
                    .btn.btn-default.btn-small.cancel=pat(:cancel)

app/views/users/new.haml
%ul.nav.nav-tabs
  %li=link_to icon_tag(:list, pat(:list)), users_index_path #url(:Users, :index)
  %li.active=link_to icon_tag(:plus, pat(:new)), users_new_path #url(:Users, :new)

.tabs-content
  = form_for :user, create_user_path, :class => 'form-horizontal' do |f|
    =partial 'users/form', :locals => { :f => f }