config/routes.rb
Rails.application.routes.draw do
  get 'admin/index', to: 'admin#index', as: :admin
  get 'search/index', to: 'search#index', as: :search
  get 'movies/index', to: 'movies#index', as: :movies
  get 'musics/index', to: 'musics#index', as: :musics
  get 'images/index', to: 'images#index', as: :images

  resources :shared_folders
  resources :users, except: [:show, :update]
  put 'user/:id/update', to: 'users#update', as: :update_user

  resources :attachments, except: [:index, :show, :create] do
    post 'authorize'
    post 'create', to: 'attachments#create', as: :create
    member do
      get 'show_image/show_image.gif', to: 'attachments#show_image'
      get 'show_thumb', to: 'attachments#show_thumb'
    end
  end

  get 'attachments/:page', to: 'attachments#index', as: :attachments
  get 'attachment/:page/show', to: 'attachments#show', as: :show_attachment


  ########  files controller #############
  post 'files/move', to: 'files#move'
  post 'files/copy', to: 'files#copy'
  post 'files/share_with', to: 'files#share_with'
  post 'files/delete', to: 'files#delete'
  post 'files/new_file', to: 'files#new_file'
  post 'files/rename', to: 'files#rename'
  post 'files/upload', to: 'files#upload'
  get 'files/download', to: 'files#download'
  get 'files/text_preview', to: 'files#text_preview'
  get 'files/preview', to: 'files#preview'
  get 'files/show_image', to: 'files#show_image'
  get 'files/show_image_thumb', to: 'files#show_image_thumb'
  get 'files/stream_file', to: 'files#stream_file'
  get 'files/video_thumb', to: 'files#video_thumb'
  ########  files controller #############



  ########  homes controller #############
  get "/", to: 'home#index'
  get :refresh_sidebar, to: 'homes#refresh_sidebar'
  ########  homes controller #############

  ########  images controller #############
  get :index, to: 'images#index'
  post :manipulate_image, to: 'images#manipulate_image'
  ########  homes controller #############

  devise_for :users
  root to: 'home#index'
end

app/models/attachment.rb
require 'pathname'
#require 'dm-serializer'
require 'open-uri'

class Attachment < ActiveRecord::Base
  has_attached_file :file,
              path: "#{Rails.root}/data/attachments/:class/:attachment/:style/:filename",
              url: "data/attachments/:class/:attachment/:style/:filename",
              :styles => {:thumb => "300x300>"}

  before_file_post_process :allow_only_images


  # # Properties
  # property :link,               String
  # property :embedded_html,      String
  # property :remote_url,         String

  belongs_to :User


  def create_thumb_if_not_exist
      if !File.exist?(self.path(:thumb)) && File.exist?(self.path)
        AC::FileUtilities.thumb_of_video(self.file.path, self.thumb_path)
    end
  end

  def thumb_path
    if !allow_only_images
      new_thumb_path = self.path(:thumb).split('.')[0..-2].join('.')+".png"
    else
      self.path(:thumb)
    end 
  end

  def allow_only_images
    if !(file.content_type =~ %r{^(image|(x-)?application)/(x-png|pjpeg|jpeg|jpg|png|gif)$})
      return false
    else
      return true
    end
  end

  def thumb_url
    Rails.application.routes.url_helpers.attachments_show_thumb_path(self.id)
    # AcHome::App.url(:attachments, :show_thumb, id: self.id)
  end

  def original_url
    Rails.application.routes.url_helpers.attachments_show_image_path(self.id)
    # AcHome::App.url(:attachments, :show_image, id: self.id)
  end

  def embedded_html?
    self.embedded_html && !self.embedded_html.empty?
  end

  def url(style=nil)
    if style
      self.file.url(style.to_sym)
    else
      self.file.url
    end
  end

  def path(style=nil)
    if style
      self.file.path(style.to_sym)
    else
      self.file.path
    end
  end

  def create_file_from_remote_url(rurl=nil)
    rurl = self.remote_url if !rurl && self.remote_url
    if rurl
      filename = rurl.split('/').last
      fileending = filename.split('.').last
      filename_widthout_ending = (filename.split('.')[0..-2] || "").join('.')
      tempfile = Tempfile.new([filename_widthout_ending, ".#{fileending}"])
      tempfile.write(Curl.get(rurl).body_str.force_encoding('utf-8'))
      self.file_file_name= filename
      self.file = tempfile
      self.remote_url = rurl
    end
    rescue Exception => e
      nil# catch url errors with validations instead of exceptions (Errno::ENOENT, OpenURI::HTTPError, etc...)
    else
      true
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  # match  '/attachments/:page'

  def index
    page = params[:page] || 1
    @attachments = current_user.attachments.page(page).per(5)
  end

  def authorize
    if  current_user.has_password?(params[:password])
      cookies['attachment_token'] ={ value: current_user.attachment_token, expires: 3.hours.from_now }
    else
      render status: 403, body: "not Authorized"
    end
  end

  def create
    @attachment = Attachment.new(params[:attachment].merge(User_id: current_user.id))
    @attachment.create_file_from_remote_url
    if @attachment.save
      @attachment.create_thumb_if_not_exist
      render json: {success: true, html: partial('/attachments/attachment', locals: {attachment: @attachment})}.to_json
    else
      render json: {success: false, error: pat(:create_error, :model => 'attachment')}.to_json
    end
  end

  def update
    @attachment = Attachment.find(params[:id])
    if @attachment && @attachment.User_id == current_user.id
      if @attachment.update(params[:User])
        render json: {success: true, html: partial('attachments/attachment', locals: {attachment: @attachment})}.to_json
      else
        render json: {success: false, error: pat(:update_error, :model => 'attachment')}.to_json
      end
    else
      render json: {success: false, error:  pat(:update_warning, :model => 'attachment', :id => "#{params[:id]}")}.to_json
    end
  end

  def destroy
    attachment = Attachment.find(params[:id])
    if attachment && attachment.User_id == current_user.id
      if attachment.destroy
        render json: {success: true}.to_json
      else
        render json: {success: false, error: pat(:delete_error, :model => 'attachment')}.to_json
      end
    else
      render json: {success: false, error: pat(:delete_warning, :model => 'attachment', :id => "#{params[:id]}")}.to_json, status: 404
    end
  end

  def show
    @attachment = Attachment.find(params[:id])
    unless @attachment.User_id == current_user.id
      render status: 403
    end
  end

  #match '/attachments/show_image/:id/show_image.gif
  def show_image
    @attachment = Attachment.find(params[:id])
    file = AcFile.new @attachment.path
    if file.path.exist? && @attachment.User_id == current_user.id
      # if Rails.env == 'production'
      #   response.headers['X-Accel-Redirect'] = file.path.to_s.sub("#{Rails.root}",'')
      #   response.headers['filename'] = file.basename.to_s
      #   response.headers['Content-Type'] = AC::FileUtilities.get_mime_type(file.path.to_s)
      #   response.headers['Content-Disposition'] = 'inline'
      #   response.headers['Cache-Control'] = "public, max-age=180"
      #   response
      # else
        # send_data(File.read(file.path), file.basename.to_s, file.mime_type)
        send_file file.path, filename: file.basename.to_s, type: file.mime_type, disposition: :'inline'
      # end
    else
      render status: 404
    end
  end

  def show_thumb
    @attachment = Attachment.find(params[:id])
    file = AcFile.new @attachment.thumb_path
    if file.path.exist? && @attachment.User_id == current_user.id
      # if Rails.env == ''
      #   response.headers['X-Accel-Redirect'] = file.path.to_s.sub("#{Rails.root}",'')
      #   response.headers['filename'] = file.basename.to_s
      #   response.headers['Content-Type'] = file.mime_type
      #   response.headers['Content-Disposition'] = 'inline'
      #   response.headers['Cache-Control'] = "public, max-age=180"
      #   response
      # else
        send_file file.path, filename: file.basename.to_s, type: file.mime_type, disposition: :'inline'
      # end
    else
      render status: 404
    end

  end

end

app/views/attachments/_attachment.haml
.attachment.pull-left.attachment_image.img-thumbnail{'data-id' => attachment.id}
	=link_to image_tag(attachment.thumb_url, class: 'thumb_image img-rounded', "data-type"=> attachment.file.content_type,'data-thumb' => attachment.thumb_url, 'data-gif'=> attachment.original_url, 'data-show_gif' => false, 'data-remote_url' => attachment.remote_url), attachment_show_path(attachment.id), 'data-show'=> attachment_show_path(attachment.id), class: 'attachment_thumb'
	-#																																																																		url(:attachments, :show, id: attachment.id)

app/views/attachments/index.haml
=link_to 'new', '#', class: 'btn btn-default new_attachment'

.attachment_pagination.row
	=paginate @attachments, params: {controller: 'attachments', action: 'index'}, :theme => 'twitter-bootstrap-3'

.attachments.row
	=render partial: '/attachments/attachment', collection: @attachments

.attachment_pagination.row
	=paginate @attachments, params: {controller: 'attachments', action: 'index'}, :theme => 'twitter-bootstrap-3'

app/views/attachments/show.haml
=link_to icon_tag('trash-o'), '#', class: 'delete_attachment btn btn-default', 'data-id' => @attachment.id
=link_to icon_tag('pencil'), '#', class: 'edit_attachment btn btn-default', 'data-id' => @attachment.id

.attachment.row{id: "attachment_#{@attachment.id}"}
	.col-md-6.attachment_image_show
		-if @attachment.remote_url =~ /webm|/
			%video{autoplay: "autoplay", loop: "loop", style: 'width: 100%'}
				%source{src: @attachment.remote_url}
		-elsif @attachment.remote_url =~ /mp4/
			%video{autoplay: "autoplay", loop: "loop", style: 'width: 100%'}
				%source{src: @attachment.remote_url}
		-else
			=image_tag(@attachment.original_url, class: 'img-rounded col-md-12')
	.col-md-6.attachment_link_show
		-if @attachment.embedded_html?
			.embedded
				-if @attachment.embedded_html.include?("iframe")
					=@attachment.embedded_html.html_safe
					:javascript 
						$('.embedded').find('iframe').removeAttr('width').addClass('col-md-12')
				-else
					%iframe.col-md-12{height: "360", frameborder: "0", src: @attachment.embedded_html}
			=link_to @attachment.link, @attachment.link, target: '_blank'
		-else
			=link_to @attachment.link, @attachment.link, target: '_blank'