config/routes.rb
Rails.application.routes.draw do
  get 'admin/index', to: 'admin#index', as: :admin
  get 'search/index', to: 'search#index', as: :search
  get 'movies/index', to: 'movies#index', as: :movies
  get 'musics/index', to: 'musics#index', as: :musics
  get 'images/index', to: 'images#index', as: :images

  resources :shared_folders
  resources :users, except: [:show, :update]
  put 'user/:id/update', to: 'users#update', as: :update_user

  resources :attachments, except: [:index, :show, :create] do
    post 'authorize'
    post 'create', to: 'attachments#create', as: :create
    member do
      get 'show_image/show_image.gif', to: 'attachments#show_image'
      get 'show_thumb', to: 'attachments#show_thumb'
    end
  end

  get 'attachments/:page', to: 'attachments#index', as: :attachments
  get 'attachment/:page/show', to: 'attachments#show', as: :show_attachment


  ########  files controller #############
  post 'files/move', to: 'files#move'
  post 'files/copy', to: 'files#copy'
  post 'files/share_with', to: 'files#share_with'
  post 'files/delete', to: 'files#delete'
  post 'files/new_file', to: 'files#new_file'
  post 'files/rename', to: 'files#rename'
  post 'files/upload', to: 'files#upload'
  get 'files/download', to: 'files#download'
  get 'files/text_preview', to: 'files#text_preview'
  get 'files/preview', to: 'files#preview'
  get 'files/show_image', to: 'files#show_image'
  get 'files/show_image_thumb', to: 'files#show_image_thumb'
  get 'files/stream_file', to: 'files#stream_file'
  get 'files/video_thumb', to: 'files#video_thumb'
  ########  files controller #############



  ########  homes controller #############
  get "/", to: 'home#index'
  get :refresh_sidebar, to: 'homes#refresh_sidebar'
  ########  homes controller #############

  ########  images controller #############
  get :index, to: 'images#index'
  post :manipulate_image, to: 'images#manipulate_image'
  ########  homes controller #############

  devise_for :users
  root to: 'home#index'
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to Rails.application.config.hostname, root_path, :class => 'navbar-brand', :title => 'Rails Admin'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

      %ul.nav.navbar-nav.navbar-right.navbar-collapse
        %li=link_to icon_tag('share-square-o'), shared_folders_path, :title => "Freigegebene Dateien verwalten", 'data-toggle'=> "tooltip", 'data-placement'=>"bottom"
        -if current_user.admin?
          %li=link_to icon_tag(:gears), admin_path, :title => "Settings", 'data-toggle'=> "tooltip", 'data-placement'=>"bottom"

        %li=link_to icon_tag(:user), edit_user_path(current_user.id), :title => "#{pat(:profile)}", 'data-toggle'=> "tooltip", 'data-placement'=>"bottom"
        %li=link_to icon_tag('sign-out'), destroy_user_session_path, method: :delete, 'data-toggle'=> "tooltip", 'data-placement'=>"bottom", title: 'ausloggen'
      :javascript
            $('ul.nav a').tooltip()

app/views/layouts/_navigation_links.html.haml
%li=link_to 'Bilder', images_path #url(:images, :index)
%li=link_to 'Videos', movies_path #url(:movies, :index)
%li=link_to 'Musik', musics_path #url(:music, :index)
%li=link_to 'Suchen', search_path #url(:search, :index)
-if true || current_user.username == 'andi'
  %li=link_to 'Attachments', attachments_path(1), :title => "Attachments", 'data-toggle'=> "tooltip", 'data-placement'=>"bottom", class: 'attachment_index_link'

app/views/layouts/application.html.haml
!!! 5
%html{:lang => 'en'}
  %head
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    %meta{:content => 'text/html; charset=utf-8', 'http-equiv' => 'Content-Type'}
    %meta{:name => :viewport, :content => 'width=device-width,initial-scale=1'}
    %title= @title.present? ? "#{@title} | Rails Admin" : "Rails Admin"
    %link{rel: 'icon', type: "'image/#{File.extname('favicon.ico').gsub('.','')}'"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

  %body{"data-current_user" => current_user.to_json, "data-Users" => User.all.map{|a| a}.to_json }
    =render partial: 'layouts/navigation'

    .container-fluid.main.main-wrapper
      #alert-row.row
        -#= {:error => 'danger', :warning => 'warning', :success => 'success', :notice => 'info'}.map do |type, class_name| flash[type.to_sym], :class => "alert alert-#{class_name} fade in", :bootstrap => true) }.join.html_safe
        =flash[:notice]
      .row-fluid
        -if ['home', 'images'].include?(params[:controller])
          .left-sidebar.col-md-3{style: "padding-left: 0px"}
            =yield :left_sidebar
        .content_wrapper{class: ['home', 'images'].include?(params[:controller]) ? 'col-md-9' : 'col-md-12'}
          .load_content.hide
            .load_icon
              =icon_tag('spinner', '', ['spin', '5x'])
            %h3='Lade Daten'
          .content
            =yield 

/* %footer */
//  .footer-wrapper.container
//    %p.pull-left
//      Copyright &copy;
//      =Time.now.year
//      Your Site - Powered by Rails v.#{Rails.version}
//    %ul.pull-right.footer-links
//      %li= link_to icon_tag(:home, 'web'), 'http://www.Railsrb.com', :target => :_blank, :class => 'footer-links-link'
//     %li= link_to icon_tag(:heart, 'blog'), 'http://www.Railsrb.com/blog', :target => :_blank, :class => 'footer-links-link'
//     %li= link_to icon_tag(:github, 'code'), 'https://github.com/Rails/Rails-framework', :target => :_blank, :class => 'footer-links-link'
//     %li= link_to icon_tag(:twitter, 'twitter'), 'http://twitter.com/Railsrb', :target => :_blank, :class => 'footer-links-link'
-if ['home', 'images'].include?(params[:controller])
  :coffeescript
    $(document).ready ()->
      $('.left-sidebar').height $(window).height() - $('.left-sidebar').offset().top - 20
      $('.load_content').height $(window).height() - $('.load_content').offset().top - 20

      $('.left-sidebar').resizable autoHide:true, ghost: true, handles: 'e', stop: (event, ui)->
        $('.left-sidebar').height($(window).height()-$('.left-sidebar').offset().top - 20)
        new_gap =(ui.size.width - ui.originalSize.width)
        if (new_gap < 0 )
          $('.content').width($('.content').width()  + Math.abs(new_gap))
        else
          $('.content').width($('.content').width()  - Math.abs(new_gap))

app/views/layouts/error.html.haml
!!! 5
%html{:lang => 'en'}
  %head
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    %meta{:content => 'text/html; charset=utf-8', 'http-equiv' => 'Content-Type'}
    %meta{:name => :viewport, :content => 'width=device-width,initial-scale=1'}
    %title= @title.present? ? "#{@title} | Rails Admin" : "#{pat(:custom_errors.title)} | Rails Admin"
    =favicon_tag 'favicon.ico'
    %link{:href => 'http://fonts.googleapis.com/css?family=Varela', :rel => :stylesheet}
    =stylesheet_link_tag 'bootstrap', 'application'
  %body
    .custom-error.text-center
      .custom-error-body.muted= yield
      .custom-error-footer
        =link_to icon_tag('arrow-left'), "#", :onclick => "history.go(-1);return false;", :class =>"custom-error-go-back btn btn-default pull-left", :title => "Go back"

app/views/layouts/railsapplication.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Ac Home'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Ac Home'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/layouts/sessions.html.haml
!!! 5
%html{:lang => 'en'}
  %head
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    %meta{:content => 'text/html; charset=utf-8', 'http-equiv' => 'Content-Type'}
    %meta{:name => :viewport, :content => 'width=device-width,initial-scale=1'}
    %title= @title.present? ? "#{@title} | Rails Admin" : "Rails Admin"
    %link{rel: 'icon', type: "'image/#{File.extname('favicon.ico').gsub('.','')}'"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

  %body{"data-current_user" => current_user.to_json, "data-Users" => User.all.map{|a| a}.to_json }
    .container-fluid.main.main-wrapper
      .content
        =yield